version: v1
plugins:
  - remote: buf.build/grpc-ecosystem/plugins/openapiv2
    out: ./tmp-swagger-gen
    opt:
      - logtostderr=true
      - simple_operation_ids=true
      - fqn_for_swagger_name=true
